name: (smart) insights from data
author: Enzo Martoglio
baseurl: http://smartinsightsfromdata.github.io/
description: by Enzo Martoglio and co.
github: http://www.github.com/smartinsightsfromdata
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: enzo@smartinsightsfromdata.com
location: 53°59'31"N  1°32'30"W
disqus: disqus_MUft83BZFK
twitter: https://twitter.com/enzomartoglio
googleplus:
linkedin: http://uk.linkedin.com/pub/enzo-martoglio/2/5a2/201/en
##Make sure to edit the above fields, especially for disqus.



markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
